### ISSUE TITLE
help: This version of the application is not configured for billing

### ISSUE THREAD

**Issue by danilomna** [loydkim/flutter_in_app#1]
hi, 

This is Danilo, I recently used your tutorial video to make IAP using flutter.
I can load the consumable product list like you ,but when I click to purchase, I receive 
and error: "This version of the application is not configured for billing"
I search the internet and tried many things, but no success. 
could you help?

**Comment by loydkim** [comment]
Hello Danilo! Thanks for watching my video.

Did you test it on the simulate device or physical? you should test it on your physical device.
And add your billing information to your google play store account.

If you have still problem, please let me know. Thank you!
